name: build
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip
  - openmm
  - numpy
  - pyyaml
  - importlib_resources
  - typing_extensions
  - xmltodict

    # Conda build
  - anaconda-client
  - conda-build
  - boa
