name: build
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip
  - openmm>=7.6
  - numpy<1.24
  - pyyaml
  - importlib_resources

    # Conda build
  - anaconda-client
  - conda-build
  - boa
