name: build
channels:
  - conda-forge
dependencies:
  # Base dependencies
  - python
  - pip
  - numpy
  - openmm
  - pyyaml

  # Conda build
  - anaconda-client
  - conda-build
  - boa

  # PyPI build
  - pip:
    - build
    - twine
