{% set version = environ['CVPACK_VERSION'][1:] %}

package:
  name: cvpack
  version: {{ version }}

source:
  git_url: ../../../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - versioningit
    - pip
  run:
    - python
    - numpy
    - openmm
    - pyyaml

test:
  imports:
    - cvpack

about:
  home: https://github.com/RedesignScience/cvpack
  summary: Useful Collective Variables for OpenMM
  description: Useful Collective Variables for OpenMM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://redesignscience.github.io/cvpack/latest
  dev_url: https://github.com/RedesignScience/cvpack
extra:
  recipe-maintainers:
    - craabreu
