package:
  name: cvpack
  version: "{{ environ['CVPACK_VERSION'] }}"

source:
  path: ../../

build:
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools
    - versioningit
    - pip
  run:
    - python >=3.8
    - importlib-resources  # [py<310]
    - numpy
    - openmm>=7.6

test:
  imports:
    - cvpack

about:
  home: https://github.com/RedesignScience/cvpack
  summary: Useful Collective Variables for OpenMM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://cvpack.readthedocs.io/en/stable
  dev_url: https://github.com/RedesignScience/cvpack

extra:
  recipe-maintainers:
    - craabreu
