name: docs
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip
  - openmm
  - sphinx
  - sphinxcontrib-bibtex
  - versioningit
  - sphinx-copybutton

    # Pip-only installs
  # - pip:
