name: docs
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - importlib_resources
  - typing_extensions
  - pip
  - openmm
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-copybutton
