name: Anaconda

on:
  push:
    branches:
      - "main"
    tags:
      - v*
  # Remove after tests:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Build on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/marketplace/actions/provision-with-micromamba
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: devtools/conda-envs/conda_build_env.yaml
          environment-name: test
          channels: conda-forge
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install package
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: Conda Build and Upload
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        shell: bash -l {0}
        working-directory: ./devtools/conda-recipes/anaconda
        run: |
          dir=$(mktemp -d)
          echo CVPACK_VERSION=$(git describe --tags | cut -d'-' -f 1)
          export CVPACK_VERSION=$(git describe --tags | cut -d'-' -f 1)
          for version in 3.{8..11}; do
            echo "Building packages for Python $version"
            outdir=$dir/py$version
            mkdir $outdir
            export PYTHON_VERSION=$version
            echo "conda mambabuild . --no-anaconda-upload -c conda-forge --output-folder $outdir --python $version"
            conda mambabuild . --no-anaconda-upload -c conda-forge --output-folder $outdir --python $version
            PACKAGE=$(find $outdir -name *.tar.bz2 | head -1)
            for platform in osx-64 linux-32 linux-64 win-32 win-64; do
              echo "conda convert --platform $platform $PACKAGE -o $outdir"
              conda convert --platform $platform $PACKAGE -o $outdir
            done
          done
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          for filename in $(find $dir -name *.tar.bz2); do
            echo "anaconda upload --user redesign-science --force --label main $filename"
            anaconda upload --user redesign-science --force --label main $filename
          done
