name: Conda Build and Publish

on:
  # release:
  #   types: ['released', 'prereleased']
  pull_request:
    branches:
      - "main"

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/build_env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.1.0
        with:
          meta_yaml_dir: devtools/conda-recipes/anaconda
          python-version: ${{ matrix.python-version }}
          platform_linux-64: true
          platform_osx-64: true
          platform_win-64: true
          user: redesign-science
          label: auto
          token: ${{ secrets.ANACONDA_TOKEN }}
